### PR TITLE
Update to doobie 1.0.0-RC5

### PR DESCRIPTION
**Pull request by limansky**

### CODE REVIEW

**Comment by lloydmeta** [comment]
Oof. Do things work if you simply exclude the dependency when adding the enumeratum-doobie lib as a dependency? 

If that works, great. Otherwise I'm going to probably think twice about RC or M dependent versions of libs.

**Comment by kovacshuni** [comment]
Release please

**Comment by lloydmeta** [comment]
> Release please

@kovacshuni does what I described in https://github.com/lloydmeta/enumeratum/pull/385#issuecomment-1836014428 work for you?

**Comment by limansky** [comment]
@lloydmeta I suppose there is no guarantee what the RC4 and RC5 are fully binary compatible. So if it works for some case it doesn't proof that it will work for another.

**Comment by lloydmeta** [comment]
Fair enough, thanks @limansky . Just pushed to Maven Central.

**Pull request merged**
