### PR TITLE
Extend 2.13 build

### PR DESCRIPTION
**Pull request by pjfanning**
* add play-json
* equivalent scala.js builds

### CODE REVIEW

**Comment by lloydmeta** [comment]
Hmm, judging from the `2.13.0-M5` [build job](https://travis-ci.org/lloydmeta/enumeratum/jobs/445166777), it doesn't look like 2.13.0-M5 compiling/testing was run for PlayJSON. I think it might be because I assumed most projects don't have 2.13 artefacts out yet and didn't use `allScalaVersions` in the `aggregateProject` function (and I think we shouldn't yet..)

https://github.com/lloydmeta/enumeratum/blob/1b0f61b49a99bb872c83db6d135bf45a3a135153/build.sbt#L628

It looks like for now, we might need to substitute `crossScalaVersions` with `scalaVersionsAll` in this segment. 

https://github.com/lloydmeta/enumeratum/blob/1b0f61b49a99bb872c83db6d135bf45a3a135153/build.sbt#L215-L260

(separate note, I just realised I completely forgot to clean up the Play JSON build def in #203 )

**Comment by lloydmeta** [comment]
Great, thanks for this :)

**Comment by lloydmeta** [comment]
Ahh, I didn't check this carefully enough; turns out we needed to add `scalaVersionsAll` to the individual project rather than the aggregate (or maybe both? meh).

After I did that, I realised that there is no `2.13.0-M5` published for play-json

```
[error] sbt.librarymanagement.ResolveException: unresolved dependency: com.typesafe.play#play-json_sjs0.6_2.13.0-M5;2.6.10: not found
[error] 	at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:332)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:208)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:239)
[error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error] 	at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error] 	at xsbt.boot.Using$.withResource(Using.scala:10)
[error] 	at xsbt.boot.Using$.apply(Using.scala:9)
```

**Comment by pjfanning** [comment]
Apologies - I haven't had much time to follow up on this. I got the play-json team to merge https://github.com/playframework/play-json/pull/194 but they mustn't have gotten around to publishing a jar.

**Pull request merged**
