### PR TITLE
Re-enable Play and Play-JSON for Scala 2.13

### PR DESCRIPTION
**Pull request by avdv**
Play 2.7.3 is around the corner, not yet officially announced.

Related to #239 

--- 

It's official :champagne: https://discuss.lightbend.com/t/play-2-7-3-released/4459

### CODE REVIEW

**Comment by lloydmeta** [comment]
Ah nice, thanks for this. Sorry for the delay, I'll take a closer look when I'm back from vacation. Looking great so far!

**Comment by lloydmeta** [comment]
Thanks !

**Comment by jtjeferreira** [comment]
@lloydmeta cant find the release in maven https://mvnrepository.com/artifact/com.beachape/enumeratum-play-json

**Comment by lloydmeta** [comment]
> @lloydmeta cant find the release in maven https://mvnrepository.com/artifact/com.beachape/enumeratum-play-json

I think it just takes time 

Screenshot 2019-06-28 at 14 16 56

**Pull request merged**
