### PR TITLE
Added anorm support for standard and value enums

### PR DESCRIPTION
**Pull request by vasyl-zhurba**
This PR adds support for Anorm's `ToStatement[_]` and `Column[_]` type classes which make it easy to use enums in sql query interpolation and sql parsers.

### CODE REVIEW

**Comment by vasyl-zhurba** [comment]
Not sure why [tests](https://travis-ci.org/lloydmeta/enumeratum/builds/509613414) didn't pass. They failed on other modules I didn't touch.

**Comment by lloydmeta** [comment]
Hey,

Thanks for the PR ! This is all great work.

I've given it some thought, and I'm leaning towards suggesting you maintain this integration on your own because quite frankly, I've never used Anorm, and probably never will. As a result, I would be a horrible steward for it..

Thoughts?

**Comment by vasyl-zhurba** [comment]
I understand your concerns.
This is my first PR to open-source project and I am not sure how I should maintain this integration on my own. Should I work and publish from forked repository, or create a brand new one?

**Comment by lloydmeta** [comment]
> I understand your concerns.
> This is my first PR to open-source project and I am not sure how I should maintain this integration on my own. Should I work and publish from forked repository, or create a brand new one?

You can always publish your own lib (doesn't need to be a fork), and publish it to Maven Central (this might be a good [starter guide](https://leonard.io/blog/2017/01/an-in-depth-guide-to-deploying-to-maven-central/))

**Pull request closed without merging**
