### PR TITLE
Bump play-json

### PR DESCRIPTION
**Pull request by markarasev**

### CODE REVIEW

**Review by lloydmeta — APPROVED** [review]
LGTM. Just waiting for the weekend to merge + release.

**Comment by gaeljw** [comment]
Shouldn't we bump to `org.playframework:play-json:3.0.0` directly?

The artifact groupId is renamed but the content is the same (https://github.com/playframework/play-json/compare/2.10.1...3.0.0).

**Comment by lloydmeta** [comment]
> Shouldn't we bump to `org.playframework:play-json:3.0.0` directly?
> 
> The artifact groupId is renamed but the content is the same ([playframework/play-json@2.10.1...3.0.0](https://github.com/playframework/play-json/compare/2.10.1...3.0.0)).

That could be bigger + separate PR that would be very welcome indeed.

**Comment by gaeljw** [comment]
I'll provide the PR today then :)

**Pull request merged**
