### PR TITLE
Update json4s to 4.0.3

### PR DESCRIPTION
**Pull request by kardapoltsev**

### CODE REVIEW

**Review by lloydmeta — APPROVED** [review]
Thanks for this. I'll set up a reminder to merge and release on the weekend.

**Comment by lloydmeta** [comment]
Merged and released as `1.7.1`

**Comment by kardapoltsev** [comment]
@lloydmeta it's still `1.7.0` in maven central. Do you use another repo for publishing?

**Comment by lloydmeta** [comment]
`enumeratum-json4s` should be at `1.7.1`; the versions are not coupled.

**Comment by kardapoltsev** [comment]
Got it, thanks!

**Pull request merged**
