### PR TITLE
Scala 2.13.0-RC2 build

### PR DESCRIPTION
**Pull request by guilgaly**
See also issue #216.

### CODE REVIEW

**Comment by lloydmeta** [comment]
Toggled this to see if we can't get Travis to build this..

**Comment by lloydmeta** [comment]
Looks like there are some build failures. In the interest of putting out an RC-release, do you mind re-targeting this to https://github.com/lloydmeta/enumeratum/tree/build/2.13-rc1?

**Comment by guilgaly** [comment]
I checked the Travis logs, apparently:

- Scala 2.10 build fails because the version of Wartremover doesn't exist for 2.10.
- Scala 2.11 build fails because of bad formatting in the `build.sbt` file (`scalafmtSbtCheck`); but I don't get why it's not an issue for the 2.12 build ?
- Scala 2.12 build succeeds.
- Scala 2.13 build fails because the various modules are missing the `enumeratum` and `enumeratum-test` dependencies. When testing locally I used `publishLocal` on the core modules and switched those dependency versions to the current snapshot version; I don't know how it's supposed to be handled normally ?

**Comment by guilgaly** [comment]
Alright, fixed the `build.sbt` formatting issue, and now the Scala 2.11 build succeeds. I'll change the target to `build/2.13-rc1` now.

**Comment by lloydmeta** [comment]
Thanks ! There are a few odd things that I think still need to be addressed (e.g. Play JSON doesn't have `2.8.0-M1` published for 2.11....) but I think this is enough to start allowing for RC builds on the branch.

**Pull request merged**
