### PR TITLE
Upgrade to 3.3.0

### PR DESCRIPTION
**Pull request by jatcwang**

### CODE REVIEW

**Comment by limansky** [comment]
You should change `.github/workflows/ci.yml` as well, to have same version in CI build.

**Comment by limansky** [comment]
@lloydmeta Is it really needed to support Scala 2.11.x in 2023? It looks like Scala Native doesn't support 2.11 since 0.4.10 (Jan 2023).

**Comment by lloydmeta** [comment]
> @lloydmeta Is it really needed to support Scala 2.11.x in 2023? It looks like Scala Native doesn't support 2.11 since 0.4.10 (Jan 2023).

I have no qualms about removing support for 2.11 (can't believe [the last release was 2017-11-09](https://www.scala-lang.org/download/2.11.0.html) 🥲 )

**Comment by limansky** [comment]
@lloydmeta I've made PR #369

**Comment by lloydmeta** [comment]
Closing this because it was handled via https://github.com/lloydmeta/enumeratum/pull/370

**Pull request closed without merging**
