### PR TITLE
Feature/scalajs

### PR DESCRIPTION
**Pull request by lloydmeta**
- Converts tests from ScalaTests to ScalaJS-compatible utest
- Make core lib publish ScalaJs JARs.

### CODE REVIEW

**Comment by lloydmeta** [comment]
Tests are currently crashing due to 

1. Coverage generation, possibly relate to https://github.com/scoverage/sbt-scoverage/issues/101
2. Scala 2.10.x issue with `compileError` from utests

**Comment by lloydmeta** [comment]
Current issues:

0. Using `compileError` from utest crashes the compiler under Scala 2.10 ((https://github.com/lihaoyi/utest/issues/68))
1. Coverage generation breaks everything, possibly relate to https://github.com/scoverage/sbt-scoverage/issues/101
2. Test report outputs are pretty useless because there are no test case names https://github.com/lihaoyi/utest/issues/69

**Comment by omidb** [comment]
is there any new update on this issue/pr ?

**Comment by lloydmeta** [comment]
@omidb , I wish there was, but the issues that I mentioned above (click through my links) have been addressed by the libraries that need to be used if we add ScalaJS support.

**Comment by lloydmeta** [comment]
Closing because ScalaJS support has been added via #23

**Pull request closed without merging**
