### PR TITLE
Bump doobie to 0.8.4

### PR DESCRIPTION
**Pull request by vpavkin**
@lloydmeta Hi! Could you, please, release a new version of enumeratum-doobie after merging this?

Thanks a lot!

### CODE REVIEW

**Comment by vpavkin** [comment]
there's no doobie for 2.11 after 0.8.0, so tests are now failing for 2.11 :(

**Comment by lloydmeta** [comment]
> there's no doobie for 2.11 after 0.8.0, so tests are now failing for 2.11 :(

I think in that case you'd need something like this, but for Doobie

https://github.com/lloydmeta/enumeratum/blob/0e19f283bbbe5bca72ae8ea7d44ed676fbc2bcdd/build.sbt#L34-L41

**Comment by vpavkin** [comment]
@lloydmeta thanks for the guidance - added proper version selection. now it looks green

**Comment by lloydmeta** [comment]
Thanks @vpavkin I've now published the latest doobie 0.8.x-based version of enumeratum-doobie.

**Comment by vpavkin** [comment]
@lloydmeta that's awesome, thank you a lot! :+1:

**Pull request merged**
