### PR TITLE
Drop Scala 2.11 support

### PR DESCRIPTION
**Pull request by limansky**

### CODE REVIEW

**Comment by limansky** [comment]
Hm, not sure why it was fail the last time, maybe some flacky test?

**Review by lloydmeta — COMMENTED** [review]
LGTM; thanks for making this a thing; I totally forgot how much special casing there was for 2.11; good riddance!!

Can you please also remove references to 2.11 from the readme 🥺

**Comment by limansky** [comment]
@lloydmeta done.

**Review by lloydmeta — APPROVED** [review]
LGTM; thanks.

**Comment by lloydmeta** [comment]
Thanks for this btw, it has been released as part of https://github.com/lloydmeta/enumeratum/releases/tag/macros-1.6.4

**Pull request merged**
