### PR TITLE
Adds support for doobie

### PR DESCRIPTION
**Pull request by alexbalonperin**
closes https://github.com/lloydmeta/enumeratum/issues/186

The tests that I added only check whether there is a Read and Write for the enum types. They do not check however that the resulting values look good. The reason is to avoid adding extra dependencies like cats-effect and using an actual database like h2 or PostgreSQL. I could add them if necessary.

Also, for the version of the enumeratum-doobie module, I am not too sure where should it start.

### CODE REVIEW

**Comment by alexbalonperin** [comment]
Not sure why the `enumeratum-cats` tests failed. @lloydmeta Is this an intermittent failure or did I break something? 🤔

**Comment by alexbalonperin** [comment]
I have tried cross-compiling the code to Scala 2.10. The latest available version of doobie supporting scala 2.10 seems to be 0.4.0. In 0.4.0, Meta was under `doobie.utils.meta`. I would have to write specific code for that version. 

Is there a way to avoid this? For example, by cross-compiling `enumeratum-doobie` only to scala 2.11 and above.

**Comment by lloydmeta** [comment]
Nice! Thanks for the PR. I’ll take a closer look when I’m back from Jp holidays :)

The tests do have intermittent failures; they’re usually the 2.10 ones and are a known issue, unfortunately.

**Comment by abalonperin** [comment]
@lloydmeta any update on this?

**Comment by lloydmeta** [comment]
> @lloydmeta any update on this?

No, not at the moment; holidays are over but I'm travelling atm. Don't worry, I will come back to this.

**Comment by lloydmeta** [comment]
Thanks for this! Just merged and released :)

**Pull request merged**
