### PR TITLE
Upgrade doobie to 1.0.0-RC4

### PR DESCRIPTION
**Pull request by jatcwang**

### CODE REVIEW

**Comment by Awethon** [comment]
@lloydmeta could you please take a look?

**Review by lloydmeta — COMMENTED** [review]
Overall LGTM, but I think the build is failing, can you please look into that?

**Comment by limansky** [comment]
It looks like reactive mongo dependency should be a RC7, without snapshot. I've created PR #366  to fix it, and update to latest RC.

**Comment by jatcwang** [comment]
1.0.0-RC4 is using Scala 3.3.0 so I think we may need to upgrade scala 3 ver here too.

**Comment by lloydmeta** [comment]
Closing this because it was handled via https://github.com/lloydmeta/enumeratum/pull/370

**Pull request closed without merging**
